config/routes.rb
Rails.application.routes.draw do
  
  root to: 'tests#index'

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  namespace :admin do
    resources :rules
    resources :badges

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end

    resources :gists, only: :index
  end
  
  resources :tests do
    post 'start', on: :member

    resources :test_passages, shallow: true do
      member do
        get 'result'
        post 'create_gist'
      end
    end

  end

  resources :badges, only: :index do
    get 'awarded', on: :collection
  end

  resources :contact_messages, only: %i[new create]
end

app/models/rule.rb
class Rule < ApplicationRecord
  belongs_to :category, optional: true
  has_many :badges

  validates :title, :method, presence: true
  validate  :method_exists?
  validates :value, absence: true, if: -> { self.method == 'first_try' }
  validates :value, presence: true, numericality: { only_integer: true, greater_than: 0 }, if: -> { ["level", "category"].include?(self.method) }
  validate  :category_exists?, if: -> { self.method == "category" }
  
  private

  def method_exists?
    errors.add :method, message: "type doesn't exist" unless BadgeAwarder::METHOD_TYPES.include?(self.method.to_sym)
  end

  def category_exists?
    errors.add :category, message: "doesn't exist" unless Category.where(id: value).pluck(:id).include?(value.to_i)
  end
end

app/controllers/admin/rules_controller.rb
class Admin::RulesController < Admin::BaseController
  before_action :find_rule, only: %i[show edit update destroy]
  
  def index
    @rules = Rule.all
  end

  def new
    @rule = Rule.new
  end

  def create
    @rule = Rule.new(rule_params)
    
    if @rule.save
      redirect_to admin_rule_path(@rule)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @rule.update(rule_params)
      redirect_to admin_rule_path(@rule)
    else
      render :edit
    end
  end

  def destroy
    @rule.destroy
    redirect_to admin_rules_path
  end

  def show
  end

  private

  def find_rule
    @rule = Rule.find(params[:id])
  end

  def rule_params
    params.require(:rule).permit(:title, :method, :value)
  end

end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/admin/rules/_form.html.erb
<div class="form-check">

<%= form_with url: (@rule.new_record? ? admin_rules_path : admin_rule_path(@rule)), model: @rule do |form| %>
    <%= form.label              :title, t('tests.index.title'), class: 'form-check-label' %> <br>
    <%= form.text_field         :title %> <br>
    <%= form.label              :method, 'Метод проверки', class: 'form-check-label' %> <br>
    <%= form.select             :method, BadgeAwarder::METHOD_TYPES.map(&:to_s), class: 'form-check-input' %> <br>
    <%= form.label              :value, class: 'form-check-label' %> <br>
    <%= form.text_field         :value %> <br>
    <br>
    <%= form.submit t('admin.save'), class: 'btn btn-primary btn-sm' %>
<% end %>
<br>
</div>

app/views/admin/rules/_rule.html.erb
  <tr>
    <td class="align-middle"><%= rule.title %></td>
    <td class="align-middle"><%= rule.badges.count %></td>
    <td class="align-middle"><%= rule.method %></td>
    <td class="align-middle"><%= rule.value %></td>
    <td class="align-middle"><%= link_to t('admin.show'), admin_rule_path(rule) %></td>
    <td class="align-middle"><%= link_to t('admin.change'), edit_admin_rule_path(rule) %></td>
    <td class="align-middle"><%= link_to t('admin.delete'), admin_rule_path(rule),
                                method: :delete,
                                data: { confirm: t('admin.confirm') } %></td>
  </tr>

app/views/admin/rules/edit.html.erb
<h2><%= t('admin.edit_rule') %></h2>
<%= render 'shared/errors', resource: @rule %>
<%= render 'form' %>

<%= link_to t('shared.back'), admin_rules_path %>

app/views/admin/rules/index.html.erb
<div class="container-fluid">
<%= link_to t('admin.new_rule'), new_admin_rule_path %>

<h2><%= t('rules.index.title') %></h2>
<table class='table table-bordered'>
<tr>
  <th class="sort-by-title pointer"><%= t('tests.index.title') %>
    <%= octicon 'arrow-up',   class: 'text-success' %>
    <%= octicon 'arrow-down', class: 'text-success' %>
  </th>
  <th><%= t('rules.index.badges_amount') %></th>
  <th>Метод</th>
  <th>Значение</th>
  <th colspan="3"><%= t('shared.actions') %></th>
</tr>
<%= render @rules %>
</table>
<br>
</div>

app/views/admin/rules/new.html.erb
<h2><%= t('admin.new_rule') %></h2>
<%= render 'shared/errors', resource: @rule %>
<%= render 'form' %>

<%= link_to t('shared.back'), admin_rules_path %>

app/views/admin/rules/show.html.erb
<h2><%= t('rules.show.rule') %> '<%= @rule.title %>'</h2> <br>

<p><strong>Метод: </strong><%= @rule.method %></p>
<p><strong>Значение: </strong><%= @rule.value %></p>

<br>

<%= link_to t('admin.change'), edit_admin_rule_path %>
<%= link_to t('shared.back'), admin_rules_path %>