config/routes.rb
Rails.application.routes.draw do
  
  root to: 'tests#index'

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  namespace :admin do
    resources :rules
    resources :badges

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end

    resources :gists, only: :index
  end
  
  resources :tests do
    post 'start', on: :member

    resources :test_passages, shallow: true do
      member do
        get 'result'
        post 'create_gist'
      end
    end

  end

  resources :badges, only: :index do
    get 'awarded', on: :collection
  end

  resources :contact_messages, only: %i[new create]
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :rule, optional: true
  has_many :badges_awardings
  has_many :users, through: :badges_awardings

  validates :title, :rule_id, :image_url, presence: true
  
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[show edit update destroy]
  
  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)
    
    if @badge.save
      redirect_to admin_badge_path(@badge)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge)
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  def show
  end

  def awarded
    @badges = current_user.badges
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :image_url, :rule_id)
  end

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  
  def index
    @badges = Badge.all
  end

  def awarded
    @badges = current_user.badges.uniq
  end

end

app/helpers/badges_helper.rb
module BadgesHelper
  def amount(badge)
    badge.recurrent == true ? "X #{BadgesAwarding.where(badge: badge, user: current_user).count}" : ''
  end
end

app/views/badges/awarded.html.erb
<div class="container-fluid">

<h2>Список полученных бэйджей</h2>

<% if @badges.present? %>
<table class='table table-bordered'>
<tr>
  <th class="sort-by-title pointer">Название
    <%= octicon 'arrow-up',   class: 'text-success' %>
    <%= octicon 'arrow-down', class: 'text-success' %>
  </th>
  <th>Изображение</th>
</tr>

<% @badges.each do |badge| %>
  <tr>
    <td class="align-middle"><%= badge.title %></td>
    <td><img width="80" height="80" src='<%= badge.image_url %>'><%= amount(badge)%></td>
  </tr>
<% end %>

<% else %>
<p>У вас пока нет бэйджей.</p>
<% end %>

</table>
<%= link_to 'Перейти к полному списку бейджей', badges_path %><br>
<%= link_to 'Перейти к тестам', tests_path %>
</div>

app/views/badges/index.html.erb
<div class="container-fluid">

<h2>Список бэйджей</h2>

<table class='table table-bordered'>
<tr>
  <th class="sort-by-title pointer">Название
    <%= octicon 'arrow-up',   class: 'text-success' %>
    <%= octicon 'arrow-down', class: 'text-success' %>
  </th>
  <th>Изображение</th>
</tr>

<% @badges.each do |badge| %>
  <tr>
    <td class="align-middle"><%= badge.title %></td>
    <td><img width="80" height="80" src='<%= badge.image_url %>'></td>
  </tr>
<% end %>

</table>
<%= link_to 'Перейти к моим бейджам', awarded_badges_path %><br>
<%= link_to 'Перейти к тестам', tests_path %>
<br>
</div>