config/routes.rb
Rails.application.routes.draw do
  
  root to: 'tests#index'

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  namespace :admin do
    resources :rules
    resources :badges

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end

    resources :gists, only: :index
  end
  
  resources :tests do
    post 'start', on: :member

    resources :test_passages, shallow: true do
      member do
        get 'result'
        post 'create_gist'
      end
    end

  end

  resources :badges, only: :index do
    get 'awarded', on: :collection
  end

  resources :contact_messages, only: %i[new create]
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true
  has_many   :badges_awardings
  has_many   :badges, through: :badges_awardings

  after_initialize  :after_initialize_set_current_question, if: :new_record?
  after_validation  :after_validation_define_next_question, on: :update, unless: :completed?

  scope :test_passages_by_user, ->(user) { where('user_id = ?', user.id) }

  PASSING_PERCENTAGE = 85.freeze

  def accept!(answer_ids)
    evaluate_answer(answer_ids)
    save
  end

  def evaluate_result!
    self.passed = self.passed?
    save
  end

  def evaluate_answer(answer_ids)
    answer_ids = [] if answer_ids.nil?
    self.correct_questions += 1 if self.current_question.answers.correct.pluck(:id).sort == answer_ids.map(&:to_i).sort
  end

  def success_percent
    ( self.correct_questions.to_f / self.test.questions.count ) * 100
  end

  def time_elapsed?
    return false unless self.test.max_time_set?
    (Time.now - self.created_at) / 60 > self.test.max_time_min
  end

  def completed?
    current_question.nil? || time_elapsed?
  end
  
  def passed?
    return false if time_elapsed?
    success_percent >= PASSING_PERCENTAGE
  end

  private

  private

  def after_initialize_set_current_question
    self.current_question = test.questions.order(id: :asc).first
  end

  def after_validation_define_next_question
    self.current_question = test.questions.where('id > ?', self.current_question).order(id: :asc).first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :set_test_passage, only: %i[ show edit update destroy result create_gist ]

  def show
    redirect_to result_test_passage_path(@test_passage) if @test_passage.completed?
  end

  def update
    @test_passage.accept!(params[:answer_ids]) 

    if @test_passage.completed?
      @test_passage.evaluate_result!
      BadgeAwarder.new(@test_passage).call
      redirect_to result_test_passage_path(@test_passage)
    else
      redirect_to @test_passage
    end
  end

  def result
    @badges = @test_passage.badges
    @test_passage.evaluate_result! if @test_passage.passed.nil? && @test_passage.completed?
  end

  def create_gist
    gist_creator = GistCreator.new(@test_passage.current_question)
    response = gist_creator.call

    if gist_creator.success? && current_user.gists.create(question_id: @test_passage.current_question.id, github_gist_id: response.id) 
      flash[:notice] = "#{ t('gists.successfully_created') } (#{view_context.link_to response.id, response.html_url})"
    else
      flash[:notice] = t('gists.error_occured')
    end

    redirect_to test_passage_path(@test_passage)
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper

  def current_question_order_number(test_passage)
    return '-' if test_passage.completed?
    test_passage.test.questions.pluck(:id).sort.index(test_passage.current_question.id) + 1
  end

  def previous_question_order_number(test_passage)
    return current_question_order_number(test_passage) if current_question_order_number(test_passage) == 1
    return test_passage.test.questions.count if test_passage.completed?
    
    current_question_order_number(test_passage) - 1 
  end

  def progress(test_passage, previous = false)
    question_order_number = previous ? previous_question_order_number(test_passage) : current_question_order_number(test_passage)

    if test_passage.completed? && previous == false
      100
    else
      (((question_order_number - 1) / test_passage.test.questions.count.to_f) * 100).ceil
    end
  end
end

app/views/test_passages/_clock.html.erb
<p><div id="testEndTime" class="hide"><%= (@test_passage.created_at + @test_passage.test.max_time_min.minutes).httpdate %></div></p>

<div id="clockdiv">
  <div>Осталось: <span class="minutes">10</span> мин. <span class="seconds">25</span> сек.</div>
</div>

<p class="Test"></p>

app/views/test_passages/_form.html.erb
<%= form_with url: test_passage_path(@test_passage), 
              local: true, 
              data:   { test_passage: @test_passage.id },
              class: "form-check",
              method: :put do |form| %>

  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
  <p>
    <%= b.check_box id: "answer_ids_#{b.object.id}", class: 'form-check-input' %> 
    <%= b.label class: 'form-check-label' %>
  </p>
  <% end %>
  

  <%= form.submit t('shared.send'), class: 'btn btn-primary btn-sm' %>

<% end %>

<br>
<%= button_to t('gists.create_gist'), create_gist_test_passage_path(@test_passage), class:"btn btn-secondary btn-sm" %>

app/views/test_passages/_progress_bar.html.erb
<div id="test-progress">
  <%= tag.div progress(@test_passage, previous = true).to_s + "%", id: "test-bar", data: { progress: progress(@test_passage), prev_progress: progress(@test_passage, previous = true) } %>
</div>

app/views/test_passages/result.html.erb
<%= render 'progress_bar' %>

<% if @test_passage.completed? %>
<h2>Прохождение теста '<%= @test_passage.test.title %>' завершено.</h2> 
  <% if @test_passage.passed %>
    <% color = "green" %>
    <% message = 'Тест пройден.' %>
  <% else %>
    <% color = "red" %>
    <% message = 'К сожалению, тест не пройден.' %>
  <% end %>

  <h3 style="color:<%= color%>;"><%= message %></h3>

  <% if @test_passage.time_elapsed? %>_
    <p>Вы не уложились в отведенное время. Попробуйте снова!</p>
  <% else %>
    <p>Вы ответили верно на <span style="color:<%= color%>"><%= number_to_percentage(@test_passage.success_percent, precision: 0) %></span> вопросов.</p>
  <% end %>

<% else %>
  <h2> Вы еще не прошли тест до конца.</h2>
  <%= link_to 'Вернуться к выполнению теста', @test_passage %>

<% end %>

<br><br>

<% if @badges.present? %>
  <h3>Поздравляем! По итогам теста вам присвоены новые бэйджи:</h3>
  <% @badges.each do |badge| %>
  <div>
    <p><%= badge.title %></p>
    <img width="80" height="80" src='<%= badge.image_url %>'></td>
  </div>
  <% end %>
<% end %>
<%= link_to 'Перейти к списку тестов', tests_path %>

app/views/test_passages/show.html.erb
<% unless @test_passage.test.max_time_min.zero? %>
<%= render 'clock' %>
<% end %>

<%= render 'progress_bar' %>

<h2>Прохождение теста '<%= @test_passage.test.title %>'</h2> 
<br>
<h4><%= @test_passage.current_question.body %> (Вопрос <%= current_question_order_number(@test_passage) %> из <%= @test_passage.test.questions.count %>)</h4>
<br>

<%= render 'form' %>

<br>
<%= link_to 'Перейти к списку тестов', tests_path %>